# Generated by Django 5.2.6 on 2025-12-03 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usuario_membresia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registro'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
