# Generated by Django 5.2.6 on 2025-12-04 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_nuevocoach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nuevocoach',
            old_name='especialiadad',
            new_name='especialidad',
        ),
    ]
